apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: backend
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "longhorn"
